### ISSUE TITLE
Project Initialisation

### ISSUE THREAD

**Issue by martinkarugaba** [martinkarugaba/pokemon-dashboard#21]
- [ ] https://github.com/martinkarugaba/pokemon-dashboard/projects/1
- [ ] There are two people on this team

**Comment by Qoosim** [comment]
#  *Status: Required Changes* :recycle: 

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Kanban board set up correctly. :heavy_check_mark: 
-  Tasks assigned fairly. :heavy_check_mark: 
-  Number of cards confirmed to be 15. :heavy_check_mark: 


![](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)


## Required Changes ♻️

- [ ] Wonderful job for setting up the kanban board for your capstone project. However, there are few things you need to modify before you can move on. I noticed that all the group tasks have no assignee. You can decide who among the team members to be assignee or every members of the group can be assigned to the group tasks. Kindly decide who to assign to those group tasks or better still assign every members of the group as assignee. This is inline with the project requirement. :point_down: 

![project-rqt](https://user-images.githubusercontent.com/26597432/218710031-860e6a0e-040c-4cdb-9290-73e967e3794a.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mckent05** [comment]
Hi team, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Good luck with your javascript capstone 👍 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
